FROM node:18-alpine

WORKDIR /app

# Копируем только package.json
COPY package.json ./

# Устанавливаем зависимости в production режиме
RUN npm ci --only=production --silent

# Копируем исходный код
COPY . .

# Генерируем Prisma клиент
RUN npx prisma generate

# Собираем приложение
RUN npm run build

# Удаляем dev зависимости
RUN npm prune --production

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
