[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm ci && npm run build"

[deploy]
startCommand = "cd backend && npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
